apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-animated-deployment
  labels:
    app: nextjs-animated
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs-animated
  template:
    metadata:
      labels:
        app: nextjs-animated
    spec:
      tolerations:
      - key: "set"
        operator: "Equal"
        value: "nextjs"
        effect: "NoSchedule"
      containers:
      - name: nextjs-animated
        image: durga51/nextjs-animated:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-animated-service
spec:
  selector:
    app: nextjs-animated
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
